version: '3.8'

networks:
  cprices:

x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '3'
  driver: json-file  

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    command: postgres -c shared_preload_libraries=timescaledb
    logging: *default-logging
    networks:
      - cprices
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data:rw
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_PASSWORD=${ROOT_PASS}
      - POSTGRES_INITDB_ARGS=--auth=password
      
  grafana:
    image: grafana/grafana:9.1.4
    container_name: grafana
    restart: unless-stopped
    logging: *default-logging
    networks:
      - cprices
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana:rw
      - ./grafana/config.ini:/etc/grafana/config.ini:ro
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./grafana/dashboards:/var/lib/grafana-dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASS}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_GITHUB_ENABLED=true
      - GF_AUTH_GITHUB_CLIENT_ID=${GITHUB_ID}
      - GF_AUTH_GITHUB_ALLOW_SIGN_UP=false
      - GF_AUTH_GITHUB_CLIENT_SECRET=${GITHUB_SECRET}
      - GF_AUTH_GITHUB_SCOPES=user:email,read:org
      - GF_AUTH_GITHUB_AUTH_URL=https://github.com/login/oauth/authorize
      - GF_AUTH_GITHUB_TOKEN_URL=https://github.com/login/oauth/access_token
      - GF_AUTH_GITHUB_API_URL=https://api.github.com/user
