version: '3.8'

networks:
  cprices:

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    command: postgres -c shared_preload_libraries=timescaledb
    networks:
      - cprices
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data:rw
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_PASSWORD=${ROOT_PASS}
      - POSTGRES_INITDB_ARGS=--auth=password
      