{
 "title": "Crypto",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "ETH USDT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  opening_price\nFROM crypto_prices\nWHERE\n  currency_pair='ETHUSDT' and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "BTC USDT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  opening_price\nFROM crypto_prices\nWHERE\n  currency_pair='BTCUSDT' and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "FIL USDT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  opening_price\nFROM crypto_prices\nWHERE\n  currency_pair='FILUSDT' and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DOGE USDT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  opening_price\nFROM crypto_prices\nWHERE\n  currency_pair='DOGEUSDT' and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}