apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    uid: TpYChz44z
    url: timescaledb:5432
    user: editor
    database: crypto
    basicAuth: false
    withCredentials: true
    isDefault: true
    jsonData:
      maxOpenConns: 10
      postgresVersion: 903
      sslmode: disable
      timescaledb: true
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsConfigurationMethod: file-path
      tlsSkipVerify: true
    secureJsonData:
      password: maexoo8ecipa8Raijeel0sil2wae7c
    version: 1
    editable: false
    